plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '1.9.22'
    id 'kotlin-kapt'
}

android {
    namespace 'com.belajar.drakor'
    compileSdk 34

    defaultConfig {
        applicationId "com.belajar.drakor"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            applicationIdSuffix ".dev"
        }
        create("staging") {
            minifyEnabled true
            debuggable true
            applicationIdSuffix ".stg"
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // Flavor dimensions
    flavorDimensions "mode"

    // Product flavors configuration
    productFlavors {
        free {
            dimension "mode"
            applicationIdSuffix = ".free"
            versionNameSuffix = "-free"
        }
        paid {
            dimension "mode"
            applicationIdSuffix = ".paid"
            versionNameSuffix = "-paid"
        }
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

//    lint {
//        baseline = file("lint.xml")
//    }

    lintOptions {
        // Memilih jenis laporan yang ingin diperiksa
        check "UnusedResources"
        // Atur opsi lainnya sesuai kebutuhan
        abortOnError false
        warningsAsErrors true
        checkReleaseBuilds true

        baseline file("lint-baseline.xml") // Konfigurasi baseline
        htmlReport true                    // Mengaktifkan laporan HTML
        htmlOutput file("build/reports/lint-results.html") // Lokasi output untuk laporan HTML
        xmlReport true                     // Mengaktifkan laporan XML
        xmlOutput file("build/reports/lint-results.xml")   // Lokasi output untuk laporan XML
        textReport true                    // Mengaktifkan laporan teks
        textOutput file("build/reports/lint-results.txt")  // Lokasi output untuk laporan teks
    }

}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.22" // Pastikan menggunakan versi Kotlin yang diperbarui
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Room dependencies
    implementation 'androidx.room:room-runtime:2.6.1'
    implementation 'androidx.room:room-ktx:2.6.1'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'com.google.android.datatransport:transport-runtime:3.3.0'
    implementation 'androidx.test:core-ktx:1.6.1'
    implementation 'androidx.test.ext:junit-ktx:1.2.1'
    kapt 'androidx.room:room-compiler:2.6.1'

    // JUnit
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Mockito
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.mockito:mockito-core:3.12.4"
    testImplementation "org.mockito:mockito-inline:3.12.4"
    testImplementation "org.mockito.kotlin:mockito-kotlin:3.2.0"

    // AndroidX Test
    testImplementation 'androidx.arch.core:core-testing:2.1.0'

    testImplementation 'org.robolectric:robolectric:4.8'


    // Coroutines Testing
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.0'

    implementation 'io.coil-kt:coil:1.4.0'
    implementation "androidx.navigation:navigation-fragment-ktx:2.4.0"
    implementation "androidx.navigation:navigation-ui-ktx:2.4.0"

    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.4.0"

    implementation "androidx.datastore:datastore-preferences:1.1.1"
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    kapt 'com.github.bumptech.glide:compiler:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'
    implementation 'com.google.code.gson:gson:2.8.6'

    implementation "androidx.work:work-runtime-ktx:2.8.1"
    implementation "io.insert-koin:koin-android:$koin_version"

    //chucker
    implementation 'com.github.chuckerteam.chucker:library:3.5.2'
    debugImplementation 'com.github.chuckerteam.chucker:library:3.5.2'
    releaseImplementation 'com.github.chuckerteam.chucker:library-no-op:3.5.2'

}
